[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["next", "react", "react-dom", "sharp"]
  included_files = []

[functions.node_bundler_flags]
  minify = true
  keep_names = false
  tree_shaking = true
  target = "node18"
  platform = "node"
  external = ["sharp"]

[build.environment]
  NEXT_RUNTIME = "nodejs"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 